### ISSUE TITLE
Update upgrade test image to have 1 or > more users in the database subscribed to various mail notifications.

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/satellite6-upgrade#109]
Recently, we hit an issue w/ internal db where product was installed from 6.0 and 6.1 and users  have subscribed to errata mail notifications.

**Comment by sghai** [comment]
more info here: https://bugzilla.redhat.com/show_bug.cgi?id=1508408#c3

**Comment by san7ket** [comment]
This was configured on the templates itself , closing this
