### ISSUE TITLE
Problem with upgrade setup, Libvirt qemu cannot be used with ssh

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/satellite6-upgrade#11]
In libvirt test cases , we use qemu+ssh://root@libvirt/system , but it seems we are facing problem while using ssh to communicate to libvirt , and we have to use qemu+tcp://root@libvirt/system to communicate with libvirt.

Proposed solution:
1) Handle it as most upgrade task, and write manipulate ssh to tcp
2) Fix the image using https://theforeman.org/manuals/1.13/index.html#5.2.5LibvirtNotes

**Comment by san7ket** [comment]
Currently one failure, But there would be more in t2

**Comment by sghai** [comment]
@san7ket : these are system tests and these should be part of tier3 instead of tier2. I don't consider this as a issue though its good to have in case we want to run such tests.
