### ISSUE TITLE
Fix PostUpgradeTestTasks running for user Satellite upgrade

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/satellite6-upgrade#111]
Currently, We are running post upgrade test tasks regardless of testrun post upgrade.

That is unnecessarily increasing the time of user specific satellite upgrade, need to fix this.

**Comment by san7ket** [comment]
Now the task will only run for product== 'longrun'

**Comment by jyejare** [comment]
We are good to close this one then. As per PR #125
