### ISSUE TITLE
Fix Capsule Sync post upgrade scenario tests

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/satellite6-upgrade#137]
The post upgrade scenario tests , add's all the lifecycle env's to capsule and then performs a Sync 
This in-turn take lot of time and capsule has no empty space left for other tests 
https://github.com/SatelliteQE/satellite6-upgrade/blob/master/upgrade_tests/test_scenarios/test_capsule.py#L266
```
E, [2018-01-18T01:49:09.109347 #2752] ERROR -- : TFTP: Failed to create PXE default file: No space left on device - /var/lib/tftpboot//pxelinux.cfg/default

[root@qe-capsule-upgrade-rhel7 ~]# df -h
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/rhel-root   94G   94G   20K 100% /
devtmpfs               5.7G     0  5.7G   0% /dev
tmpfs                  5.7G   12K  5.7G   1% /dev/shm
tmpfs                  5.7G   25M  5.7G   1% /run
tmpfs                  5.7G     0  5.7G   0% /sys/fs/cgroup
/dev/vda1              497M  202M  295M  41% /boot
tmpfs                  1.2G     0  1.2G   0% /run/user/0
```

**Comment by san7ket** [comment]
@jyejare Can you look into this , it consumes too much time and resources of upgrade

**Comment by san7ket** [comment]
Capsule Synced content

![screen](https://user-images.githubusercontent.com/14175952/35661979-85969636-070d-11e8-8047-41e70ddb3e2b.png)

**Comment by jyejare** [comment]
The referenced PR is merged ... Hence closing this issue.
