### ISSUE TITLE
Add another DB to db test matrix

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/satellite6-upgrade#159]
We need to add another DB-CS in our db upgrade test matrix. First see if we can easily restore. Fore more info: ping sghai :)

**Comment by sghai** [comment]
@sthirugn : yeah.. that db requires some tweaking to readily use with for upgrade. At first we need to generate custom certs to actually restore it. I saw some comment from Mike that there is an instnace running internally with same db, we can take backup of that for further testing.

I'll follow-up with Mike on that.

**Comment by ntkathole** [comment]
@sghai shall we close this...We have DB-CS now.

**Comment by sghai** [comment]
@ntkathole : Yeah.. thanks for follow-up and making it part of test matrix.

**Comment by sthirugn** [comment]
thank you @sghai and @ntkathole
