### ISSUE TITLE
Upgrade needs to move to using RHV 4 API and not RHV 3 API

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/satellite6-upgrade#187]
Will update more info soon.

**Comment by kbidarkar** [comment]
Current message from our RHEVM1 setup shows the below stuff:

```
Client from address "10.8.119.1" is using version 3 of the API, which has been deprecated since version 4.0 of the engine, and will no longer be supported starting with version 4.3. Make sure to update that client to use a supported versions of the API and the SDKs, before upgrading to version 4.3 of the engine.
```

**Comment by kbidarkar** [comment]
Why is this critical and needs attention now?

1) `satellite6-upgrade` uses `ovirt-engine-sdk-python==3.6.8.0` which in turn uses RHEV3 API
2) rhevm1 is now upgraded to RHV4.2 and seen from above comment, RHEV3 API support will not be available from RHV4.3
3) We can and will hold on upgrading rhevm1 to RHV4.3, but at some point, this needs to get upgraded, to the latest version.
4) Also, consider the new infra that we will be building, we may not want it to be locked onto RHV4.2.

So, We should start the move to RHV4 API now, so that we can smoothly move forward without any issues.

**Comment by kbidarkar** [comment]
Moving to RHV4 API, would also help with the move to Python3 .
We have another issue for this, #162

**Comment by sghai** [comment]
Jitendra will look into it.

**Comment by jyejare** [comment]
Closing this as relevant PR #189 is merged.
