### ISSUE TITLE
Issue: Parameterized Tests testname is appending with data

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/satellite6-upgrade#2]
$subject creates an issue in creating a trend for the testcase in jenkins. The results of tests needs to be altered by removing appended data to the test name.

**Comment by rochacbruno** [comment]
You can pass `ids` parameter

```python
@pytest.mark.parametrize(
    "pre,post",
    compare_postupgrade('activation-key', 'content view')
   ids=['id_for_pre', 'id_for_post']
)
```

`ids` can be also a callable receiving `x` as `[function, parameter]`

```python
@pytest.mark.parametrize(
    "pre,post",
    compare_postupgrade('activation-key', 'content view')
   ids=lambda x: x[0].__name__ + x[1]
)
```

**Comment by jyejare** [comment]
@rochacbruno , Thanks for the solution, that works.

**Comment by jyejare** [comment]
@rochacbruno , What do you think about this approach any updates/suggestions - https://github.com/SatelliteQE/satellite6-upgrade/compare/master...jyejare:pytest_ids?expand=1

**Comment by rochacbruno** [comment]
@jyejare nice solution, is that giving the desired output?

**Comment by jyejare** [comment]
@rochacbruno Yes, it is !
