### ISSUE TITLE
Define parameters with array/hash values in upgrade images

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/satellite6-upgrade#206]
bz: https://bugzilla.redhat.com/show_bug.cgi?id=1618378

**Comment by omaciel** [comment]
Great to see us being proactive here! @jyejare how is this coming along? @sghai what is the priority?

**Comment by jyejare** [comment]
@omaciel , I had a plan to move all upgrade scenario tests to robottelo so that we can use existing written function in robottelo. And hence reducing the duplicate efforts.

But if its that urgent, I won't bother to duplicate the code.

**Comment by ntkathole** [comment]
Fixed!
