### ISSUE TITLE
Users who have modified the default role will fail to upgrade to foreman

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/satellite6-upgrade#212]
Users who have modified the default role will fail to upgrade to foreman
1.17  on the db:seed stage or unexpectedly change the default role.

Users who have added permissions to the default role will see one of two
issues:
- If the permission has no filters (i.e. unlimited), the permission will be
removed from the default role silently.
- If the permission has a filter set (e.g. "location = TLV"), the upgrade
will fail with the following error:
NoMethodError: undefined method `id' for nil:NilClass

more info: https://bugzilla.redhat.com/show_bug.cgi?id=1621029

**Comment by sghai** [comment]
@jyejare : do we have test cases around default role modification ?

**Comment by ntkathole** [comment]
Fixed!
