### ISSUE TITLE
Enable rex on capsule

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/satellite6-upgrade#213]
https://bugzilla.redhat.com/show_bug.cgi?id=1621134

```
# satellite-installer --scenario capsule --enable-foreman-proxy-plugin-remote-execution-ssh 
Installing             Done                                               [100%] [...............................................................]
  Success!
  * Capsule is running at https://qe-capsule-feature:9090
  The full log is at /var/log/foreman-installer/capsule.log

# rpm -qa | grep tfm-rubygem-net-scp
tfm-rubygem-net-scp-1.1.0-7.el7sat.noarch
```

**Comment by san7ket** [comment]
[root@qe-capsule-upgrade-rhel7 ~]# satellite-installer --scenario capsule --enable-foreman-proxy-plugin-remote-execution-ssh
Installing             Done                                               [100%] [................................................................................................................................]
  Success!
  * Capsule is running at https://qe-capsule-upgrade-rhel7.capqe.lab.eng.rdu2.redhat.com:9090
  The full log is at /var/log/foreman-installer/capsule.log
[root@qe-capsule-upgrade-rhel7 ~]# rpm -qa | grep tfm-rubygem-net-scp
tfm-rubygem-net-scp-1.1.0-7.el7sat.noarch
