### ISSUE TITLE
RH SCL Product Search(using nailgun) from Upgrade Image instance is broken

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/satellite6-upgrade#260]
When I attempt to search the rhscl product from satellite upgrade image instance, it asks for organization field even though it is passed.
```
In [1]:  org = entities.Organization(id=1).read()
In [2]:  entities.Product(name='Red Hat Software Collections (for RHEL Server)', organization=org).search()
TypeError: A value must be provided for the "organization" field.
```

Interestingly, the issue is only noted in the Default Organization. In other org it works.

**Comment by ntkathole** [comment]
@jyejare I feel this is the issue in nailgun itself. This behaviour is observed only with the product which is added to sync plan.
