### ISSUE TITLE
Multiple calls to yum plugin loader

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/satellite6-upgrade#288]
Please tackle this issue on priority:

https://bugzilla.redhat.com/show_bug.cgi?id=1625649

- Register a host with server
- update katello-agent package
- Clear yum cache and run a yum repolist

there shouldn't be multiple calls to yum plugin loader, like below:

Loaded plugins: product-id, subscription-manager
Loaded plugins: product-id, subscription-manager
Loaded plugins: product-id, subscription-manager
Loaded plugins: product-id, subscription-manager
Loaded plugins: product-id, subscription-manager

@jyejare @vijay8451 : lets see if we can tackle it as part of upgrade scenarios.

**Comment by vijay8451** [comment]
@sghai Yes we could cover this under upgrade scenario in post_upgrade. under customer scenario sheet same is also mentioned already.
