### ISSUE TITLE
Upgrade RHEL7 image and add RHEL8 on docker upgrade system

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/satellite6-upgrade#297]
**In order to see the more compatibility with latest releases it is worth to upgrade RHEL7 image and add RHEL8 on docker upgrade system.**

**Comment by vijay8451** [comment]
@jyejare any thought on above .

**Comment by jyejare** [comment]
+1 @vijay8451 , we should update rhel image and use rhel8 beta for time being until released.

**Comment by vijay8451** [comment]
- Upgraded image of RHEL7.2 to RHEl7.6
- Added RHEL8-beta
