### ISSUE TITLE
Add coverage for incremental publish of rpm repo

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/satellite6-upgrade#309]
Recently we hit issue https://bugzilla.redhat.com/show_bug.cgi?id=1698549 after upgrade from 6.4 to 6.5. Good candidate for scenario tests.

**Comment by vijay8451** [comment]
@ntkathole thanks to raise this one . we already following the almost same way test here:
https://github.com/SatelliteQE/robottelo/blob/master/tests/upgrades/test_contentview.py#L58-L300
the only pending part on that is to port with robottelo (which I shall take care soon)
