### ISSUE TITLE
Need to remove repository check from foreman-upgrade --white-list.  

### ISSUE THREAD

**Issue by devendra104** [SatelliteQE/satellite6-upgrade#316]
foreman-maintain upgrade failed to enable the repository if we passed "repositories-setup" in whitelist part.
`foreman-maintain upgrade run --whitelist="disk-performance, repositories-setup" `

This issue occurs only if we select the distribution through CDN.

**Comment by ntkathole** [comment]
@devendra104 we add this change before 6.5 GA. Isssue is tracked at https://github.com/SatelliteQE/satellite6-upgrade/issues/312 . Can you please raise PR to revert it?

**Comment by ntkathole** [comment]
Fixed
