### ISSUE TITLE
Nailgun API failed to perform sync operation.

### ISSUE THREAD

**Issue by devendra104** [SatelliteQE/satellite6-upgrade#327]
Nailgun API dump an error "Required lock is already taken by other running tasks.\nPlease inspect their state, fix their errors and resume" of self-created sync task.
 
```
entities.Repository(id=scl_repo.id).sync()
WARNING:nailgun.client:Received HTTP 500 response: {"displayMessage":"Required lock is already taken by other running tasks.\nPlease inspect their state, fix their errors and resume them.\n\nRequired lock: read\nConflicts with tasks:\n- https://XYZ.com/foreman_tasks/tasks/cbb29433-e289-472b-ac96-8649778d6977","errors":["Required lock is already taken by other running tasks.\nPlease inspect their state, fix their errors and resume them.\n\nRequired lock: read\nConflicts with tasks:\n- https://XYZ.com/foreman_tasks/tasks/cbb29433-e289-472b-ac96-8649778d6977"]}
```

**Comment by jyejare** [comment]
As we discussed yday, we came to the conclusion that somehow repo sync task is failing with 'lock already taken' warning. But the fact is that the lock is of that task itself.

And probably this is worth discussing with devs or logging a bug.

**Comment by vijay8451** [comment]
@devendra104 as checked with you this is happing because of syncplan running reposync on every mins( looks more a bug with syncplan) hence remove the product from syncplan (until bug fix) and run reposync manually.

**Comment by jyejare** [comment]
No @devendra104 if you remember we debug and tried repo sync manually using 'nailgun in python interactive mode', we concluded https://github.com/SatelliteQE/satellite6-upgrade/issues/327#issuecomment-500702958 at the end. :)

**Comment by vijay8451** [comment]
@jyejare this is syncplan bug(hourly) as it's running on every mins and same is causing ' 'lock already taken' warning' because another tasks was running when you tried to sync the repos and same time when you checked it over UI there was no running task .

Could you please take a look at upgrade box tasks and see 'sync1' tasks status (they are running every mins for same repo) .. you will get this issue :)

**Comment by devendra104** [comment]
> As we discussed yday, we came to the conclusion that somehow repo sync task is failing with 'lock already taken' warning. But the fact is that the lock is of that task itself.
> 
> And probably this is worth discussing with devs or logging a bug.

Agree, Same has observed today morning, but after saving the saved sync plan this issue was disappeared. 
I recreated the templates by using satellite VM and restarted the upgrade job but 
yet now didn't observe this issue.

**Comment by devendra104** [comment]
> @devendra104 as checked with you this is happing because of syncplan running reposync on every mins( looks more a bug with syncplan) hence remove the product from syncplan (until bug fix) and run reposync manually.

Yes, but after re-saving the sync plan this issue was disappeared.
If this issue occurs again will file a new bugzilla for the same.

**Comment by jyejare** [comment]
Ohh, I was not known that the sync-plan running every minute. Anyways its good that we fixed it.

**Comment by devendra104** [comment]
@jyejare @vijay8451 this issue will be taken care in https://bugzilla.redhat.com/show_bug.cgi?id=1721055.

**Comment by jyejare** [comment]
Thanks for the update @devendra104 .

**Comment by ntkathole** [comment]
Fixed!
