### ISSUE TITLE
Disabling and Enabling the sync plan in Capsule to avoid Bugzilla 1721055

### ISSUE THREAD

**Issue by devendra104** [SatelliteQE/satellite6-upgrade#328]
Upgrade operation was getting failed because scheduled sync blocking sync_capsule_repos_to_upgrade triggered sync plan.
To avoid this problem we put disable sync plan at the beginning of this module and once the task execution will be done we enable the sync plan.
WARNING:nailgun.client:Received HTTP 500 response: {"displayMessage":"Required lock is already taken by other running tasks.\nPlease inspect their state, fix their errors and resume them.\n\nRequired lock: read\nConflicts with tasks:

**Comment by ntkathole** [comment]
Fixed!
