### ISSUE TITLE
Currently `Customer Scenarios Pre/Post` tests are failing due docker host is having high load on it.

### ISSUE THREAD

**Issue by vijay8451** [SatelliteQE/satellite6-upgrade#361]
Currently `Customer Scenarios Pre/Post` tests are failing due docker host is having high load on it.

Hence  requires to increase the resource on it as below to avoid it in future:
```
     Current   =>    Increase 
RAM    8GB               12-16GB
CPU     2                     4
```

**Comment by jyejare** [comment]
Wish Granted ! :)

Increased to 16GB and 4 CPU, but its a temporary solution. We need to find out the smarter solution.

**Comment by vijay8451** [comment]
> Wish Granted ! :)
> 
> Increased to 16GB and 4 CPU, but its a temporary solution. We need to find out the smarter solution.

yeah it is , and after above if we hit same then shall  go with below as well:

 - A teardown for containers cleaner 
 - If still found same issue then separate docker hosts sat version wise ..

Above looks a the next long term approach to me :)

**Comment by jyejare** [comment]
Also, removed some unused/unnecessary images:
```
  655  docker rmi test/rhel8beta:latest
  997  docker rmi registry.access.redhat.com/rhel8-beta/rhel:latest
 1000  docker rmi fedora:latest
 1001  docker rmi fedora:28
 1002  docker rmi jacobcallahan/genvirt:latest
 1005  docker rmi registry.access.redhat.com/rhel6.8:latest
 1006  docker rmi registry.access.redhat.com/rhel7.2:latest
 1008  docker rmi upgrade:rhel8beta
 1011  docker rmi upgrade:rhel74
```
This should help in making things smooth !
