### ISSUE TITLE
[High] Update metadata for existence tests

### ISSUE THREAD

**Issue by ntkathole** [SatelliteQE/satellite6-upgrade#375]
We need to update the component of existence tests as we did for robottelo so that we can have component owner name in polarion for each test case.

**Comment by ntkathole** [comment]
@sghai @jyejare fyi, any comments before I will move ahead?

**Comment by jyejare** [comment]
@ntkathole Yes you can change the same but people don't need to afraid as how to fix the failures, I will do it this time and will KT others for upcoming release.
