### ISSUE TITLE
Skip Satellite Existence tests with Bugs

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/satellite6-upgrade#43]
Skip existence test 'test_positive_hosts_by_mac'  due to BZ 1289510.

**Comment by jyejare** [comment]
@rochacbruno , Please let me know when you implement skip_if_bug decorator in robozilla, as this issue is blocked on to it.

**Comment by jyejare** [comment]
Skip TEST "test_content_host_with_installable_erratta" with bug id : 1461397.

**Comment by jyejare** [comment]
Skip TEST "test_positive_cvs_by_repository_ids" with bug id: 1461026

**Comment by jyejare** [comment]
Skip TEST 'test_positive_organizations_by_description' with bug id : 1461455

**Comment by jyejare** [comment]
@rochacbruno Please let me know when you finish the implementation of skip_if_bug decorator, Its on high priority for upgrade tests here.

**Comment by rochacbruno** [comment]
@jyejare once the PR https://github.com/SatelliteQE/robozilla/pull/28 is merged and `robozilla 0.1.8` released to PyPI you will be able to do.

```python
from robozilla.decorators import bz_bug_is_open
```

optionally it accepts 

`sat_version_picker=function_returning_string` 

and `config_picker=function_returning_a_dict_with_bz_credentials`

Take a look at robozilla.decorators docstrings once merged.

**Comment by rochacbruno** [comment]
Created https://github.com/SatelliteQE/robozilla/pull/30 to address this issue

**Comment by jyejare** [comment]
PR #97  has been raised to fix this issue.
