### ISSUE TITLE
Run capsule sync post upgrade

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/satellite6-upgrade#47]
I see many issues related to capsule sync w/ recent snaps so would be a good candidate for automation to monitor it.

**Comment by jyejare** [comment]
I think we can add a scenario test here in our upgrade scenario tests.

**Comment by sghai** [comment]
@jyejare : Sure

**Comment by jyejare** [comment]
I propose two scenarios here:

Scenario1: Test package added to satellite preupgrade is synced to capsule post upgrade.

- Steps:
    1) Before Satellite upgrade, Sync a repo/rpm in satellite.
    2) Upgrade satellite/capsule.
    3) Run capsule sync post upgrade.
    4) Check if the repo/rpm is been synced to capsule.

Scenario2: Test package added postupgrade is snyced to capsule post upgrade.

- Steps:
    1) Upgrade Satellite/Capsule.
    2) Sync a repo/rpm in satellite.
    3) Run capsule sync.
    4) Check if the repo/rpm is been synced to capsule.

**Comment by jyejare** [comment]
The reference PR #63 is already merged so closing this issue
