### ISSUE TITLE
Add support to pass custom upgrade installer options to standalone-upgrade 

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/satellite6-upgrade#48]
Bug:https://bugzilla.redhat.com/show_bug.cgi?id=1425437

Upstream commit: https://github.com/bbuckingham/katello-installer/blob/009c33d62593f343948f01dc803641387a1fd79f/hooks/boot/30-upgrade.rb

**Comment by sghai** [comment]
@san7ket : why we wanted to add that. I think by default it will fixes the mismatches.

**Comment by san7ket** [comment]
@sghai yes , but we have a new option to test atm. This also helps bug verification, to test new options if any added in future :)

**Comment by sghai** [comment]
@san7ket : thanks..I was about to file a new issue for same. The idea was to test puppet upgrade. In case we wanted to upgrade puppet3 -> puppet4. So this issue solves that as well.

**Comment by san7ket** [comment]
The puppet upgrade support is added
