### ISSUE TITLE
Client upgrade fails, when done with docker containers

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/satellite6-upgrade#5]
Issue copied from https://github.com/SatelliteQE/automation-tools/issues/585

Currently, same docker vm is used to create , containers for rhel6 and rhel7 upgrade. These upgrades when ran concurrently, may result in deletion of containers created by each other.
Solution: We can create a clean-up job which can be run periodically to delete these containers.

**Comment by sghai** [comment]
Please fix this on priority post 6.2.9

**Comment by san7ket** [comment]
PR Merged , closing this
