### ISSUE TITLE
Increase the memory on Docker VM 

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/satellite6-upgrade#57]
As, upgrade is triggered for every snaps and the frequency of builds and snaps have increase. Running clean-up job every alternate day is not enough.
Planning to increase memory on Docker VM

**Comment by san7ket** [comment]
Increase it to 12 Gb, lets see how it works.

**Comment by jyejare** [comment]
@san7ket , You mean you have increase**d** it to 12 GB , or you want us to increase.

**Comment by san7ket** [comment]
Increased It
