### ISSUE TITLE
Update the upgrade automation to reboot satellite and capsule only after complete upgrade

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/satellite6-upgrade#69]
Recently, we hit w/ a bz where we were rebooting the satellite after yum update though that raised some severe issues w/ Satellite upgrade procedure itself. 

So please update the automation where we will perform upgrade only after complete upgrade instead of after `yum update -y`

In short it should be like:
```
    katello-service stop
    yum upgrade
    satellite-installer --upgrade
    reboot
```

**Comment by JacobCallahan** [comment]
Why add the reboot after the installer finishes?

**Comment by san7ket** [comment]
PR merged , closing this
