### ISSUE TITLE
As part of client upgrade test. include a package install on client through satellite

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/satellite6-upgrade#70]
I think this issue may validate if qpid is behaving correctly once package install on client through satellite succeeds.

**Comment by sghai** [comment]
Please make sure to cover below cases w/ both satellite and capsule.

1) perform a package action on an old (pre-upgrade registered) client
2) register and perform a package action on a new client

**Comment by san7ket** [comment]
1. a) Keep the client on lesser version , maybe z-1.
    b) Upgrade the client and then perform package action

**Comment by jyejare** [comment]
@san7ket @sghai , Both the scenarios are taken care of:

1. Package installation on 'FROM_VERSION' client from 'TO_VERSION' satellite.
2. Package Installation on 'TO_VERSION' client from 'TO_VERSION' satellite.
