### ISSUE TITLE
Run capsule sync once upgrade is successfully finished

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/satellite6-upgrade#72]
would like to cover this as part of Jenkins job.

**Comment by san7ket** [comment]
This can be achieved by adding into post_upgrade task in the job itself 
https://github.com/SatelliteQE/satellite6-upgrade/blob/master/upgrade/helpers/tasks.py#L297

**Comment by san7ket** [comment]
The above PR is merged and we have capsule sync as part of the upgrade job
