### ISSUE TITLE
Have discovery images for upgrade_el6 and upgrade_el7

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/satellite6-upgrade#76]
Discovery related tests failing to find these images on libvirt and test's failing.

**Comment by rplevka** [comment]
ok, the current approach is, that we have a re-mastered `FDI` iso for every pipeline (excepting upgrade one, which hasn't been created yet).

This approach has a downside of not testing the very recent version of FDI, so here's my proposal:

Let's create a simple jenkins job that would wget the FDI.rpm from the devel server, extract the `iso` and run the `discovery-image-remaster` command to generate appropriate up-to-date isos for each pipeline. I would add this to the release-pipeline chain.

This way, we'll find a bottle of fresh milk on our doorstep every morning.

**Comment by sghai** [comment]
Please see if you guys can accomplish this.

**Comment by ntkathole** [comment]
Raised a PR in automation tools https://github.com/SatelliteQE/automation-tools/pull/643

**Comment by ntkathole** [comment]
This will get resolved by PR #145

**Comment by san7ket** [comment]
Done
