### ISSUE TITLE
Loganalyzer gets stuck with too many files or no file

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/satellite6-upgrade#83]
If Loganalyzer has too many files , or if no log file is found. It utilizes the whole bandwidth and the established connection is stuck.

**Comment by renzon** [comment]
Is there at least some logs around it so I can take a look?

**Comment by omaciel** [comment]
@san7ket ping?

**Comment by san7ket** [comment]
@omaciel it was stuck in loganalyzer phase , when the size of /var/log/messages was >4M. 
The ssh session get's stuck, possible reasons

1. Trying to send the results back to jenkins
2. Trying to compute on logs 

I will try to get the logs on the next run to share.
@renzon could we add some INFO messages in loganalyzer , to pin point as to what is causing this.

**Comment by renzon** [comment]
@san7ket. Hum, so maybe the log size can have a performance issue. I need to dig where, when searching for errors or when accessing diff content. Do still have the log file and the link for the job? This way I can see many lines were generated during the upgrade and can reproduce locally with no need to a satellite box.

**Comment by san7ket** [comment]
The latest fix from @renzon fixed the issue.
