### ISSUE TITLE
Update capsule upgrade cmd and certificate regeneration cmd for Capsules during upgrade

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/satellite6-upgrade#98]
Generating Certs
=============
Add --certs-update-all to the capsule-certs-generate command, for example:
```
  capsule-certs-generate --certs-tar ~/tmp/mycerts.tar.gz
 --foreman-proxy-fqdn pipeline-capsule-6-2-rhel7.woodford.example.com
 --certs-update-all
```

Upgrading Capsule
 ================
 When upgrading the capsule, with our updated certs bundle, we need to
 ensure these new certs are deployed and the nssdb is regenerated. Do this
 by ensuring '--certs-regenerate true' and --'certs-deploy true' and
 '--certs-update-all' are included in the upgrade command. For example:

``` 
 satellite-installer --upgrade --foreman-proxy-content-certs-tar
 ~/mycerts.tar.gz --certs-update-all --certs-regenerate true --certs-deploy
 true
```

NOTE: that this applies to 6.2 to 6.3 upgrades and will not apply to 6.3 to 6.3.z upgrades when we reach that point.

**Comment by sghai** [comment]
@jyejare : we need this change before next snap.

**Comment by jyejare** [comment]
@san7ket , Thanks for looking into it.
